### ISSUE TITLE
Demo2 is corrupted

### ISSUE THREAD

**Issue by orhun** [ratatui/ratatui#1721]
## Description

While looking at the docs, I realized the demo2 example does not work as expected:

![](https://raw.githubusercontent.com/ratatui/ratatui/images/examples/demo2.gif)

It doesn't toggle the tabs and the mascot eye is shown at the wrong cell.

Then I realized we don't actually handle the tab key:

```
diff --git a/examples/apps/demo2/src/app.rs b/examples/apps/demo2/src/app.rs
index fc01e595..b541469e 100644
--- a/examples/apps/demo2/src/app.rs
+++ b/examples/apps/demo2/src/app.rs
@@ -93,7 +93,7 @@ impl App {
         match key.code {
             KeyCode::Char('q') | KeyCode::Esc => self.mode = Mode::Quit,
             KeyCode::Char('h') | KeyCode::Left => self.prev_tab(),
-            KeyCode::Char('l') | KeyCode::Right => self.next_tab(),
+            KeyCode::Char('l') | KeyCode::Right | KeyCode::Tab => self.next_tab(),
             KeyCode::Char('k') | KeyCode::Up => self.prev(),
             KeyCode::Char('j') | KeyCode::Down => self.next(),
             KeyCode::Char('d') | KeyCode::Delete => self.destroy(),

```

But still, it's corrupted (generated via `vhs`):

![Image](https://github.com/user-attachments/assets/1af7a154-c5fa-4676-8d86-547a24b1cfe9)

**Comment by joshka** [comment]
Weird. Maybe git bisect to find out when the problem was introduced? Guessing somewhere in the module split / examples stuff.

**Comment by orhun** [comment]
The thing is I can't reproduce it in my terminal... only happens in VHS.

Can you maybe confirm this on your side as well?

**Comment by joshka** [comment]
Works fine on my mac:
```sh
$ vhs --version              
vhs version 0.9.0
$ vhs examples/vhs/demo2.tape
```

![Image](https://github.com/user-attachments/assets/caebc24b-b90d-43ea-be20-bb3b818be9ab)

**Comment by orhun** [comment]
Okay, the tab is still not working but it's fixable. The corruption is probably caused by my setup - not sure what though. I tried different terminal emulators, no luck. I'm using the same version of `vhs` as you.

I don't remember if we have talked about this but how about generating the GIFs in the CI (via [`vhs-action`](https://github.com/charmbracelet/vhs-action) and push to the `images` branch automatically?

**Comment by joshka** [comment]
> I don't remember if we have talked about this but how about generating the GIFs in the CI (via [`vhs-action`](https://github.com/charmbracelet/vhs-action) and push to the `images` branch automatically?

The problem with this approach was that generating a gif has some non-deterministic parts (even if there's no change). This will mean potentially blowing up the repo with commits. Likely this would be order of magnitude gigabytes per 100 commits.

**Comment by joshka** [comment]
yup will do

**Comment by orhun** [comment]
I guess this went under the radar and Josh is away recently...

@j-g00da when you have time, can you generate the GIF and check if it looks okay on your side?

```
vhs examples/vhs/demo2.tape
```

We can then commit that to the `images` branch.

**Comment by j-g00da** [comment]
Corrupted for me with vhs 0.10.0
Will try downgrading to 0.9

![Image](https://github.com/user-attachments/assets/ab184e8b-44f3-4e2c-b712-f2d49513b8c2)

**Comment by orhun** [comment]
It's still broken with 0.9 for me

**Comment by orhun** [comment]
I tried generating the GIF from the CI with this workflow:

```yml
name: vhs
on:
  push:
    branches:
      - vhs-test

jobs:
  vhs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@6d653acede28d24f02e3cd41383119e8b1b35921 # master
        with:
          toolchain: stable

      - uses: actions/setup-go@v6
        with:
          go-version: "^1.13.1"

      - run: |
          cargo build -p demo2
          sudo apt update
          sudo apt install -y ffmpeg ttyd
          go install github.com/charmbracelet/vhs@latest
          vhs ./examples/vhs/demo2.tape

      - name: Upload GIF artifact
        uses: actions/upload-artifact@v4
        with:
          name: demo2-gif
          path: ./target/demo2.gif
```

<sup>

VHS action is broken currently: https://github.com/charmbracelet/vhs-action/issues/459

</sup>

However the result is still corrupted:

![Image](https://github.com/user-attachments/assets/65b64678-9e42-4850-a82f-682a8db2ed2c)
